import QueryProvider from '@/provider/query-client';
import type { Metadata, Viewport } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Repo Me - Find Your Repository',
  description: 'Generated by love - mfxxna dev',
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased overflow-x-hidden relative bg-[#0F0F0F]`}
      >
        <QueryProvider>
          <main className="min-h-screen py-4">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
